### ISSUE TITLE
Support for devices with multiple outputs

### ISSUE THREAD

**Issue by off-my-lawn** [tim-hellhake/tasmota-adapter#30]
Just bought myself a [power board](https://templates.blakadder.com/mirabella_genio_I002340.html)

Using the template {"NAME":"Genio i002340","GPIO":[56,0,0,0,21,22,0,0,23,17,24,25,0],"FLAG":0,"BASE":18} the Web UI gives me 5 independent controls. One for each power point plus the USB ports.

When configuring using the tasmota adapter I can only control the state for the first one.

`10:41:33 RSL: stat/tasmota/RESULT = {"Time":"2020-06-09T10:41:33","Uptime":"0T00:18:26","UptimeSec":1106,"Heap":29,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":21,"MqttCount":0,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","POWER4":"OFF","POWER5":"OFF","Wifi":{"AP":1,"SSId":"redacted","BSSId":"10:13:31:DD:45:D1","Channel":6,"RSSI":72,"Signal":-64,"LinkCount":1,"Downtime":"0T00:00:08"}}`

The tasmota log shows only power1 being accessed.
`10:46:10 RSL: stat/tasmota/RESULT = {"POWER1":"OFF"}`

Not a high priority for me.

**Comment by tim-hellhake** [comment]
Have you enabled `multiple relay channels` in the config?
After that, you should see all 5 devices.

**Comment by tim-hellhake** [comment]
The state of the properties might not be updated, though.
I'm fixing this at the moment.

**Comment by tim-hellhake** [comment]
Did you have a chance to test it @off-my-lawn?

**Comment by theo-inf** [comment]
I'm not sure if my advice is in the right place. If it is wrong, I apologize.

I also use a socket strip with tasmota firmware (AOFO 4CH with USB).

is there a possibility to change the names of the individual channels? Because with my power strip the "Channel 1" button switches all channels and not the "All" button. Furthermore you don't always know what is connected to which channel. Speaking names would therefore be a relief.

Thank you very much for your great work!

**Comment by off-my-lawn** [comment]
Sorry, I haven't had a chance to look. I think the errors I'm getting are something going wrong on my home wifi (I can't get a single device to operate through the adapter). Just haven't had a chance to properly investigate.

With two devices powered on I get this in my logs. (Web UI for both devices is working)

2020-06-15 23:20:27.323 INFO   : About to call startPairing on TasmotaAdapter
2020-06-15 23:20:27.460 INFO   : tasmota-adapter: Unhandled Rejection
2020-06-15 23:20:27.461 ERROR  : tasmota-adapter: { FetchError: request to http://192.168.0.239:80/ failed, reason: connect EINVAL 192.168.0.239:80 - Local (0.0.0.0:0)
2020-06-15 23:20:27.462 ERROR  : tasmota-adapter:     at ClientRequest.<anonymous> (/home/pi/.mozilla-iot/addons/tasmota-adapter/node_modules/node-fetch/lib/index.js:1455:11)
2020-06-15 23:20:27.463 ERROR  : tasmota-adapter:     at ClientRequest.emit (events.js:198:13)
2020-06-15 23:20:27.463 ERROR  : tasmota-adapter:     at Socket.socketErrorListener (_http_client.js:401:9)
2020-06-15 23:20:27.464 ERROR  : tasmota-adapter:     at Socket.emit (events.js:198:13)
2020-06-15 23:20:27.464 ERROR  : tasmota-adapter:     at emitErrorNT (internal/streams/destroy.js:91:8)
2020-06-15 23:20:27.465 ERROR  : tasmota-adapter:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
2020-06-15 23:20:27.465 ERROR  : tasmota-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-06-15 23:20:27.466 ERROR  : tasmota-adapter:   message:
2020-06-15 23:20:27.466 ERROR  : tasmota-adapter:    'request to http://192.168.0.239:80/ failed, reason: connect EINVAL 192.168.0.239:80 - Local (0.0.0.0:0)',
2020-06-15 23:20:27.467 ERROR  : tasmota-adapter:   type: 'system',
2020-06-15 23:20:27.467 ERROR  : tasmota-adapter:   errno: 'EINVAL',
2020-06-15 23:20:27.468 ERROR  : tasmota-adapter:   code: 'EINVAL' }
2020-06-15 23:21:27.328 INFO   : Pairing timeout

If I power the device that gave that error completely off, I get an error for the second device.
2020-06-15 23:22:43.140 INFO   : About to call startPairing on TasmotaAdapter
2020-06-15 23:22:43.343 INFO   : tasmota-adapter: Unhandled Rejection
2020-06-15 23:22:43.345 ERROR  : tasmota-adapter: { FetchError: request to http://192.168.0.47:80/ failed, reason: connect EINVAL 192.168.0.47:80 - Local (0.0.0.0:0)
2020-06-15 23:22:43.346 ERROR  : tasmota-adapter:     at ClientRequest.<anonymous> (/home/pi/.mozilla-iot/addons/tasmota-adapter/node_modules/node-fetch/lib/index.js:1455:11)
2020-06-15 23:22:43.347 ERROR  : tasmota-adapter:     at ClientRequest.emit (events.js:198:13)
2020-06-15 23:22:43.348 ERROR  : tasmota-adapter:     at Socket.socketErrorListener (_http_client.js:401:9)
2020-06-15 23:22:43.349 ERROR  : tasmota-adapter:     at Socket.emit (events.js:198:13)
2020-06-15 23:22:43.350 ERROR  : tasmota-adapter:     at emitErrorNT (internal/streams/destroy.js:91:8)
2020-06-15 23:22:43.351 ERROR  : tasmota-adapter:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
2020-06-15 23:22:43.352 ERROR  : tasmota-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-06-15 23:22:43.353 ERROR  : tasmota-adapter:   message:
2020-06-15 23:22:43.354 ERROR  : tasmota-adapter:    'request to http://192.168.0.47:80/ failed, reason: connect EINVAL 192.168.0.47:80 - Local (0.0.0.0:0)',
2020-06-15 23:22:43.355 ERROR  : tasmota-adapter:   type: 'system',
2020-06-15 23:22:43.356 ERROR  : tasmota-adapter:   errno: 'EINVAL',
2020-06-15 23:22:43.362 ERROR  : tasmota-adapter:   code: 'EINVAL' }

**Comment by tim-hellhake** [comment]
@theo-inf

> I'm not sure if my advice is in the right place. If it is wrong, I apologize.

No need to apologize, I'm always happy to help :)

> is there a possibility to change the names of the individual channels? Because with my power strip the "Channel 1" button switches all channels and not the "All" button. Furthermore you don't always know what is connected to which channel. Speaking names would therefore be a relief.

Unfortunately, that's currently not possible.
The gateway knows `devices` and `properties`.
You can only change the `title` of a `device` in the UI of the gateway.
The channels are `properties` of a tasmota `device`.
I could change the `name` of the `property` in the adapter, but there is no UI where you could let me know which names I should use.
The only quick solution I see would be to expose all tasmota devices as a list in the config of the adapter.
But I'm affright that would completely overload the config menu.
What do you think?

> Thank you very much for your great work!

Thank you very much :)

**Comment by tim-hellhake** [comment]
> 2020-06-15 23:20:27.466 ERROR : tasmota-adapter: 'request to http://192.168.0.239:80/ failed, reason: connect EINVAL 192.168.0.239:80 - Local (0.0.0.0:0)',
2020-06-15 23:20:27.467 ERROR : tasmota-adapter: type: 'system',
2020-06-15 23:20:27.467 ERROR : tasmota-adapter: errno: 'EINVAL',
2020-06-15 23:20:27.468 ERROR : tasmota-adapter: code: 'EINVAL' }

`EINVAL` is a standard Linux error constant for `invalid argument`.
If that happens on a connect call there is usually a problem with the supplied address or address family.
As I didn't touch the network code and the adapter worked on your system before I assume something happened to your network config.
The IP address looks ok to me but I don't know your network topology.
Can you access `http://192.168.0.239:80` from your PC?

**Comment by off-my-lawn** [comment]
In short, it was a problem with my pi. I could connect to it but it couldn't connect to anything. Possibly because it was confused with both ethernet and wifi.

Now that I can see the result, it's not quite what I was hoping for.

If I scan a light I get two devices that I can add even though it's physically one device. (eg. tasmota-7103 and tasmota-7103.local-color)

In my ideal world it would give me a device for each of the 5 relays, and take the default name for each of them from the friendlyname command. (Which could also be used to assign nicer names for the properties of the current device) Then again, I'm more than capable of making that world a reality. :)

**Comment by tim-hellhake** [comment]
> If I scan a light I get two devices that I can add even though it's physically one device. (eg. tasmota-7103 and tasmota-7103.local-color)

I already thought about removing the redundant device, but I wasn't sure if it breaks something.

> In my ideal world it would give me a device for each of the 5 relays

I think I could add an option to create a dedicated device for every channel.
It won't be the default setting because some people may already rely on the current configuration.
Would that work for you?

> and take the default name for each of them from the friendlyname command

Using the `friendlyname` as `title` seems to be a good idea in general.
Thanks for the tip.

> Which could also be used to assign nicer names for the properties of the current device

As I understand it, there is only one `friendlyname`.
Would you use the same name for all properties?
My idea was to use the `friendlyname` for the device title.

**Comment by off-my-lawn** [comment]
From Tasmota 8.2.0 friendly name reports the name for all channels.
eg.
`01:10:57 RSL: RESULT = {"FriendlyName1":"Lounge Heater","FriendlyName2":"Tasmota2","FriendlyName3":"Tasmota3","FriendlyName4":"Google Home Mini","FriendlyName5":"Tasmota5","FriendlyName6":"Tasmota6","FriendlyName7":"Tasmota7","FriendlyName8":"Tasmota8"}`

From Tasmota 8.3.1 there is a command DeviceName
eg.
`01:13:57 RSL: RESULT = {"DeviceName":"Lounge Powerboard"}`

So, if we add this behaviour it needs to degrade nicely for older versions.

**Comment by tim-hellhake** [comment]
With the next update, the adapter should use the corresponding FriendlyName as the name of the channel property.
If there is only one channel then the FriendlyName is used as device name.

@theo-inf
Would this solve your problem or do you need to change the names in the gateway?

@off-my-lawn
Can you please test if it works for you?

**Comment by tim-hellhake** [comment]
@off-my-lawn Did you have a chance to test it?

**Comment by tim-hellhake** [comment]
I'm closing this now.
If you have any further problems please report back.
